apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfix-notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfix-notes-api
  template:
    metadata:
      labels:
        app: gfix-notes-api
    spec:
      imagePullSecrets:
          - name: devops101registry-credentials
      containers:
        - name: notes-api
          image: devops101registry.azurecr.io/gfix-notes-api:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gfix-notes-api
spec:
  type: LoadBalancer
  selector:
    app: gfix-notes-api
  ports:
      - protocol: TCP
        port: 80
